function out = LgH_func(x)
global constants
sigma = constants.sigma;
psi = 0; % an extra constant from prior verions
r = x(1:2); phi = x(3);
out = [(-cos(phi)*(r(1)^3+sigma*wrap_angle(atan2(r(2),r(1))-phi)*r(2)+r(1)*r(2)^2)...
        -(sigma*wrap_angle(-atan2(r(2),r(1))+phi)*r(1)+r(1)^2*r(2)+r(2)^3)*sin(phi))/((r(1)^2 ...
        +r(2)^2)*sqrt(psi^2*sigma-sigma*wrap_angle(atan2(r(2),r(1))-phi)^2+r(1)^2+r(2)^2)), ...
    (sigma*wrap_angle(-atan2(r(2),r(1))+phi))/sqrt(psi^2*sigma ...
        -sigma*wrap_angle(atan2(r(2),r(1))-phi)^2+r(1)^2+r(2)^2)];
end